{
 "title": "Home Assistant",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_sensor_unit_percent{entity=\"sensor.disk_use_percent\"}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_sensor_unit_percent{entity=\"sensor.memory_use_percent\"}"
    }
   ]
  },
  {
   "title": "Processor temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_sensor_temperature_celsius{entity=\"sensor.processor_temperature\"}"
    }
   ]
  },
  {
   "title": "Free space on disk ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_sensor_data_size_gib{entity=\"sensor.disk_free\"}"
    }
   ]
  },
  {
   "title": "Used disk / in %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_sensor_unit_percent{entity=\"sensor.disk_use_percent\"}"
    }
   ]
  }
 ]
}