{
 "title": "Keenetic_monitoring",
 "description": "Keenetic Voyager Pro dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Keenetic в серверной",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"keen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\n  |> filter(fn: (r) => r[\"hostname\"] == \"Keenetic-3872\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Объём Swap-файла",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"keen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"swapfree\")\n  |> filter(fn: (r) => r[\"hostname\"] == \"Keenetic-3872\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Загрузка процессора",
   "type": "timeseries",
   "description": "Загрузка процессора на точке доступа",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"keen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpuload\")\n  |> filter(fn: (r) => r[\"hostname\"] == \"Keenetic-3872\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Свободная память точки доступа",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"keen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"memfree\")\n  |> filter(fn: (r) => r[\"hostname\"] == \"Keenetic-3872\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Температура точки доступа",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"keen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"keen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface stat\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rxspeed\")\n  |> filter(fn: (r) => r[\"name\"] == \"AccessPoint\" or r[\"name\"] == \"AccessPoint_5G\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Download",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"keen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface stat\")\n  |> filter(fn: (r) => r[\"_field\"] == \"txspeed\")\n  |> filter(fn: (r) => r[\"name\"] == \"AccessPoint\" or r[\"name\"] == \"AccessPoint_5G\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  { "title": "Advanced", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Downloaded bytes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"keen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"txbytes\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"AccessPoint\" or r[\"name\"] == \"AccessPoint_5G\" or r[\"name\"] == \"GigabitEthernet0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 5m)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Uploaded bytes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"keen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rxbytes\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"AccessPoint\" or r[\"name\"] == \"AccessPoint_5G\" or r[\"name\"] == \"GigabitEthernet0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 5m)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Donwloaded by device",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"keen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ip hotspot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"txbytes\")\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Upload by device",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"keen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ip hotspot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rxbytes\")\n  |> group(columns: [\"name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}