services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    env_file:
      - stack.env
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
    # use a named, managed volume for data volume
    - mc_forge:/data
    # attach local host directory "mods" in same directory as this compose file
    # all mods in this directory get copied into /data/mods at startup
    - /home/alexander/homeapps/minecraft-server/mods:/mods:ro

  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "12h"
      # instead of network_mode below, could declare RCON_HOST
      # RCON_HOST: mc
    volumes:
    # mount the same volume used by server, but read-only
    - mc_forge:/data:ro
    # use a host attached directory so that it in turn can be backed up
    # to external/cloud storage
    - /home/alexander/mc-backups:/backups
    # share network namespace with server to simplify rcon access
    network_mode: "service:mc"

  monitor:
    image: itzg/mc-monitor
    command: export-for-prometheus
    environment:
      EXPORT_SERVERS: mc
      GATHER_INTERVAL: 10s
      GATHER_TELEGRAF_ADDRESS: telegraf:8094
      GATHER_SERVERS: mc.hypixel.net
      DEBUG: "true"

volumes:
  # declared the named volume, but use default/local storage engine
  mc_forge: {}
