global:
  scrape_interval: 30s
scrape_configs:
  - job_name: node
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: "hass"
    scrape_interval: 60s
    metrics_path: /api/prometheus

    # Long-Lived Access Token
    bearer_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjOWU0NGFkMjIwYmQ0OTE1OWFiOTYwMDQyOGRmOTFlMiIsImlhdCI6MTcyNDE5MzE1NSwiZXhwIjoyMDM5NTUzMTU1fQ.v8phXF1hV1VVo_kfi13pP37_xDFxVVPAWhipnW-ZJOs"

    scheme: http
    static_configs:
      - targets: ['192.168.1.42:8123']

  - job_name: mc-monitor
    static_configs:
      - targets: ['monitor:8080']
      - targets: ['cadvisor:8080']