global:
  scrape_interval: 30s
scrape_configs:
  - job_name: node
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: "hass"
    scrape_interval: 60s
    metrics_path: /api/prometheus

    # Long-Lived Access Token
    bearer_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI0YTI0MjZmNGQxMjc0ZjNkYWU4NDQ1OWIwYzFhNDg5NCIsImlhdCI6MTcyNDMzMDEzMiwiZXhwIjoyMDM5NjkwMTMyfQ.odyGVeiXXiqteQ1YdQMVr2GjMjMnNAUByC_tfmWlTz0"

    scheme: http
    static_configs:
      - targets: ['192.168.1.42:8123']

  - job_name: mc-monitor
    static_configs:
      - targets: ['monitor:8080']
      - targets: ['cadvisor:8080']
