services:
  # не работает в россии
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/alexander/radarr/config:/config
      - /srv/samba/share/jellyfin/movies:/movies #optional
      - /srv/samba/share/transmission/result:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped 

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    env_file:
      - stack.env
    volumes:
      - /home/alexander/transmission/data:/config
      - /srv/samba/share/transmission/result:/downloads
      - /srv/samba/share/transmission/torrents:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    env_file:
      - stack.env
    volumes:
      - /home/alexander/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - /home/alexander/jellyfin/config:/config
      - /home/alexander/jellyfin/cache:/cache
      - type: bind
        source: /srv/samba/share/jellyfin
        target: /media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - stack.env
    volumes:
      - /home/alexander/sonarr:/config
      - /srv/samba/share/jellyfin/Shows:/tv #optional
      - /srv/samba/share/transmission/result:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - VERSION=docker
    env_file:
      - stack.env
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - /home/alexander/plex/library:/config
      - /srv/samba/share/jellyfin/Shows:/tv
      - /srv/samba/share/jellyfin/Movies:/movies
    restart: unless-stopped
