services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - AUTO_UPDATE=true
    volumes:
      - /home/alexander/jackett/data:/config
      - /srv/samba/share/transmission:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
