apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: InfluxDB_v2_Keenetic
    type: influxdb
    access: proxy
    url: http://192.168.1.136:8086/
    jsonData:
      version: Flux
      organization: influxdb
      defaultBucket: keen
      tlsSkipVerify: true
    secureJsonData:
      token: 4udwL1tmi54Wpc9NBHItePi1-iKWcUN4wK0DZ1KriJaTaU5BXrGuhh_zEPhVSMcvss4R0A7R2f8cKGms5SFydw==