
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create directory for Photoprism
      file:
        path: "/srv/samba/share/photoprism"
        state: directory
        owner: "alexander"
        group: "alexander"
        mode: 777

    - name: Create directory for Photoprism
      file:
        path: "/srv/samba/share/photoprism/images"
        state: directory
        owner: "alexander"
        group: "alexander"
        mode: 777

    - name: Stop existing services
      command: docker compose -f ../photoprism/docker-compose.yml up -d

    - name: Create and start services
      command: docker compose -f ../photoprism/docker-compose.yml up -d
